param(
    [ValidatePattern('^\d+\.\d+\.\d+$')]
    [string]$Version
)

# Prepares the Wago / CurseForge listing texts. Writes ONLY into .agents/listing/ (git-ignored). No network access.
# The project description is evergreen (docs/store-description.md, no version number); what changed per
# release goes into the changelog, which the release workflow uploads with every file.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$tocPath = Join-Path $root 'WoWraVox.toc'
$descriptionPath = Join-Path $root 'docs/store-description.md'
$outDir = Join-Path $root '.agents/listing'
$publishedHashPath = Join-Path $outDir '.published-hash'

$toc = Get-Content -LiteralPath $tocPath
function Get-TocField([string]$Name) {
    $line = $toc | Where-Object { $_ -match "^##\s*$([regex]::Escape($Name)):\s*(.+?)\s*$" } | Select-Object -First 1
    if ($line) { $Matches[1] } else { '' }
}
if (-not $Version) { $Version = Get-TocField 'Version' }
if ($Version -notmatch '^\d+\.\d+\.\d+$') { throw "No valid version (parameter or TOC): '$Version'" }
$wagoId = Get-TocField 'X-Wago-ID'
$curseId = Get-TocField 'X-Curse-Project-ID'

if (-not (Test-Path -LiteralPath $descriptionPath)) { throw 'docs/store-description.md is missing.' }
$description = ([System.IO.File]::ReadAllText($descriptionPath) -replace "`r`n", "`n").TrimEnd() + "`n"
if ($description -match '\b\d+\.\d+\.\d+\b') { throw 'docs/store-description.md must not contain a version number.' }

$notes = & (Join-Path $PSScriptRoot 'Get-ChangelogSection.ps1') -Version $Version
$notes = ($notes | Out-String).Trim()

# Hash of the description as normalised above; compared with the hash stored after the last manual sync.
$sha = [System.Security.Cryptography.SHA256]::Create()
$hash = ([System.BitConverter]::ToString($sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($description)))).Replace('-', '').ToLowerInvariant()
$published = if (Test-Path -LiteralPath $publishedHashPath) { (Get-Content -LiteralPath $publishedHashPath -Raw).Trim() } else { '' }
$descriptionChanged = $hash -ne $published
$syncLine = if ($descriptionChanged) {
    'The description CHANGED since the last sync (or was never synced): update it on Wago and CurseForge, then store the hash (see the last line).'
} else {
    'The description is unchanged since the last sync: nothing to do on the store pages except checking the new file entry and its changelog.'
}

$checklist = @"
# Listing checklist (release $Version)

Generated by ``tools/New-ListingText.ps1``. The release workflow uploads the ZIP and the changelog text with every file; only the project page itself is manual.

Project IDs from the TOC: Wago ``$wagoId``, CurseForge ``$curseId``.

## Every release

- [ ] Wago: the new file shows version $Version with the changelog from ``release-notes.md``.
- [ ] CurseForge: the new file shows "WoWraVox $Version" with the changelog. A new file can show "in review" for a while; re-check later instead of re-uploading.
- [ ] GitHub: release ``v$Version`` has the ZIP and the same notes.

## Only when the description changed

$syncLine

- [ ] Wago Addons: replace the project description with ``wago-description.md``.
- [ ] CurseForge: replace the project description with ``curseforge-description.md`` and check the formatting after pasting.
- [ ] Store the hash: write ``$hash`` into ``.agents/listing/.published-hash``.

## Only when the look or features changed

- [ ] Screenshots (taken by hand, in-game, English UI): options overview, aura rule with Apply/Expire, TTS panel, item rule in slot mode, charge rule, collapsed Expiration panel.
- [ ] Logo: ``docs/branding/WoWraVoxIcon.png`` (small variant ``WoWraVoxIcon_small.png``).
- [ ] GitHub "Homepage" field (About box) points to the CurseForge or Wago project page.

Description hash now: ``$hash``
"@

New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$utf8 = New-Object System.Text.UTF8Encoding($false)
$files = [ordered]@{
    'wago-description.md'        = $description
    'curseforge-description.md'  = $description
    'release-notes.md'           = $notes
    'CHECKLIST.md'               = $checklist
}
foreach ($name in $files.Keys) {
    $text = ($files[$name] -replace "`r`n", "`n").TrimEnd() + "`n"
    [System.IO.File]::WriteAllText((Join-Path $outDir $name), $text, $utf8)
    Write-Output (Join-Path $outDir $name)
}
Write-Output ("Description {0} (hash {1})." -f $(if ($descriptionChanged) { 'changed' } else { 'unchanged' }), $hash.Substring(0, 12))
