param(
    [ValidatePattern('^\d+\.\d+\.\d+$')]
    [string]$Version
)

# Generates listing texts for the Wago / CurseForge pages from README.md + CHANGELOG.md.
# Writes ONLY into .agents/listing/ (git-ignored). No network access.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$tocPath = Join-Path $root 'WoWraVox.toc'
$readmePath = Join-Path $root 'README.md'
$outDir = Join-Path $root '.agents/listing'

$toc = Get-Content -LiteralPath $tocPath
function Get-TocField([string]$Name) {
    $line = $toc | Where-Object { $_ -match "^##\s*$([regex]::Escape($Name)):\s*(.+?)\s*$" } | Select-Object -First 1
    if ($line) { $Matches[1] } else { '' }
}
if (-not $Version) { $Version = Get-TocField 'Version' }
if ($Version -notmatch '^\d+\.\d+\.\d+$') { throw "No valid version (parameter or TOC): '$Version'" }
$wagoId = Get-TocField 'X-Wago-ID'
$curseId = Get-TocField 'X-Curse-Project-ID'

$readme = [System.IO.File]::ReadAllText($readmePath) -split "\r?\n"

# Lines under "## <Heading>" up to the next level-2 heading (### subsections stay), blank edges trimmed.
function Get-ReadmeSection([string]$Heading) {
    $start = -1
    for ($i = 0; $i -lt $readme.Count; $i++) {
        if ($readme[$i] -match ('^##\s+' + [regex]::Escape($Heading) + '\s*$')) { $start = $i + 1; break }
    }
    if ($start -lt 0) { throw "README.md has no '## $Heading' section." }
    $end = $readme.Count
    for ($i = $start; $i -lt $readme.Count; $i++) { if ($readme[$i] -match '^##\s') { $end = $i; break } }
    $lines = @($readme[$start..($end - 1)])
    while ($lines.Count -and [string]::IsNullOrWhiteSpace($lines[0])) { $lines = @($lines | Select-Object -Skip 1) }
    while ($lines.Count -and [string]::IsNullOrWhiteSpace($lines[-1])) { $lines = @($lines | Select-Object -SkipLast 1) }
    $lines -join "`n"
}

$title = ($readme | Where-Object { $_ -match '^#\s+(.+?)\s*$' } | Select-Object -First 1) -replace '^#\s+', ''
$intro = ($readme | Select-Object -Skip 1 | Where-Object { $_ -notmatch '^#' -and -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -First 1)
if (-not $title -or -not $intro) { throw 'README.md title or intro paragraph not found.' }
$repoUrl = [regex]::Match(($readme -join "`n"), 'https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+').Value
if (-not $repoUrl) { throw 'GitHub repository URL not found in README.md.' }

$whatItDoes = Get-ReadmeSection 'What it does'
$firstLaunch = Get-ReadmeSection 'First launch'
$usage = Get-ReadmeSection 'Usage'
$installReadme = Get-ReadmeSection 'Installation'
# Short installation: manual line + README's downgrade note and WowUp hint (skip the repo-folder copy line).
$downgrade = ($installReadme -split "`n" | Where-Object { $_ -like 'Downgrading:*' } | Select-Object -First 1)
$wowup = ($installReadme -split "`n" | Where-Object { $_ -like 'In WowUp,*' } | Select-Object -First 1)
$installLines = @(
    "Install through the Wago or CurseForge app, through WowUp, or manually: download the ZIP from the [latest release]($repoUrl/releases/latest) and extract the ``WoWraVox`` folder into ``Interface/AddOns``, then run ``/reload`` in WoW Retail."
)
if ($wowup) { $installLines += $wowup }
if ($downgrade) { $installLines += $downgrade }
$installation = $installLines -join "`n`n"

function New-Description {
    @(
        "# $title",
        $intro,
        "Version $Version.",
        "## What it does`n`n$whatItDoes",
        "## First launch`n`n$firstLaunch",
        "## Usage`n`n$usage",
        "## Installation`n`n$installation",
        "## Links`n`n- Source code and issues: $repoUrl`n- Releases: $repoUrl/releases`n- Report a bug: $repoUrl/issues"
    ) -join "`n`n"
}

$notes = & (Join-Path $PSScriptRoot 'Get-ChangelogSection.ps1') -Version $Version
$notes = ($notes | Out-String).Trim()

$checklist = @"
# Listing checklist for $title $Version

Generated by ``tools/New-ListingText.ps1``. The release workflow uploads the ZIP and the changelog section only; everything below is manual.

Project IDs from the TOC: Wago ``$wagoId``, CurseForge ``$curseId``.

## Texts in this folder

- ``wago-description.md`` -> Wago Addons: project description.
- ``curseforge-description.md`` -> CurseForge: project description.
- ``release-notes.md`` -> identical to the changelog text the workflow sends to GitHub, Wago and CurseForge (check it appears on each file entry).

## Wago Addons (manual)

- [ ] Description: paste ``wago-description.md``.
- [ ] Screenshots: upload the list below.
- [ ] Logo: upload ``docs/branding/WoWraVoxIcon.png``.
- [ ] Check that the new file shows version $Version with the changelog.

## CurseForge (manual)

- [ ] Description: paste ``curseforge-description.md`` and check the formatting after pasting.
- [ ] Screenshots: upload the list below.
- [ ] Logo: upload ``docs/branding/WoWraVoxIcon.png``.
- [ ] Moderation status: a new file can show "in review" for a while; the project page does not list it as downloadable until approved. Re-check later instead of re-uploading.

## GitHub (manual)

- [ ] Repository "Homepage" field (About box): set to the CurseForge or Wago project page (empty today). Description/topics: check once.

## Screenshot suggestions (in-game, English UI)

| File name | Shows |
| --- | --- |
| ``01-options-overview.png`` | Options window with a few rules in the list |
| ``02-aura-rule-apply-expire.png`` | Aura rule editor with Apply and Expire text/sound settings |
| ``03-tts-panel.png`` | Text-to-Speech panel (voice, speed, volume) |
| ``04-item-slot-rule.png`` | Item rule with "Track the slot, not the item" (Trinket 1) |
| ``05-holy-armaments.png`` | Holy Armaments charge rule |
| ``06-expiration-panel-collapsed.png`` | Expiration panel collapsed (plus icon and hint) |

Logo source: ``docs/branding/WoWraVoxIcon.png`` (small variant: ``docs/branding/WoWraVoxIcon_small.png``).
"@

New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$utf8 = New-Object System.Text.UTF8Encoding($false)
$files = [ordered]@{
    'wago-description.md'        = (New-Description)
    'curseforge-description.md'  = (New-Description)
    'release-notes.md'           = $notes
    'CHECKLIST.md'               = $checklist
}
foreach ($name in $files.Keys) {
    $text = ($files[$name] -replace "`r`n", "`n").TrimEnd() + "`n"
    [System.IO.File]::WriteAllText((Join-Path $outDir $name), $text, $utf8)
    Write-Output (Join-Path $outDir $name)
}
